<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>SnipCopy</AssemblyName>
    <RootNamespace>SnipCopy</RootNamespace>
    <ApplicationIcon>SnipCopy.ico</ApplicationIcon>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <DefineConstants>$(DefineConstants);SDK_RECORDING</DefineConstants>
  </PropertyGroup>
</Project>
